import {AchievementDifficulty, MediaType} from "@/lib/server/utils/enums";


export const mangaAchievements = [
    {
        codeName: "completed_manga",
        name: "Finish Line Hero",
        description: "Awarded for completing manga, because you have more commitment to them than your real-life relationships",
        mediaType: MediaType.MANGA,
        tiers: [
            { criteria: { count: 10 }, difficulty: AchievementDifficulty.BRONZE },
            { criteria: { count: 30 }, difficulty: AchievementDifficulty.SILVER },
            { criteria: { count: 80 }, difficulty: AchievementDifficulty.GOLD },
            { criteria: { count: 150 }, difficulty: AchievementDifficulty.PLATINUM },
        ],
    },
    {
        codeName: "rated_manga",
        name: "Opinionated Otaku",
        description: "Awarded for rating manga, because everyone needs to know your totally professional 2AM judgment calls.",
        mediaType: MediaType.MANGA,
        tiers: [
            { criteria: { count: 10 }, difficulty: AchievementDifficulty.BRONZE },
            { criteria: { count: 30 }, difficulty: AchievementDifficulty.SILVER },
            { criteria: { count: 50 }, difficulty: AchievementDifficulty.GOLD },
            { criteria: { count: 100 }, difficulty: AchievementDifficulty.PLATINUM },
        ],
    },
    {
        codeName: "comment_manga",
        name: "Keyboard Warrior Sensei",
        description: "Awarded for commenting manga, because typing 'OMG THAT PLOT TWIST!!1!' is literary criticism now.",
        mediaType: MediaType.MANGA,
        tiers: [
            { criteria: { count: 10 }, difficulty: AchievementDifficulty.BRONZE },
            { criteria: { count: 30 }, difficulty: AchievementDifficulty.SILVER },
            { criteria: { count: 50 }, difficulty: AchievementDifficulty.GOLD },
            { criteria: { count: 100 }, difficulty: AchievementDifficulty.PLATINUM },
        ],
    },
    {
        codeName: "author_manga",
        name: "Stalker-san",
        description: "Awarded for completing manga from the same author, because following someone's entire career isn't creepy at all.",
        mediaType: MediaType.MANGA,
        tiers: [
            { criteria: { count: 2 }, difficulty: AchievementDifficulty.BRONZE },
            { criteria: { count: 3 }, difficulty: AchievementDifficulty.SILVER },
            { criteria: { count: 4 }, difficulty: AchievementDifficulty.GOLD },
            { criteria: { count: 5 }, difficulty: AchievementDifficulty.PLATINUM },
        ],
    },
    {
        codeName: "publisher_manga",
        name: "Corporate Loyalty",
        description: "Awarded for completing manga from the same publisher, because brand loyalty is totally a personality trait.",
        mediaType: MediaType.MANGA,
        tiers: [
            { criteria: { count: 3 }, difficulty: AchievementDifficulty.BRONZE },
            { criteria: { count: 5 }, difficulty: AchievementDifficulty.SILVER },
            { criteria: { count: 8 }, difficulty: AchievementDifficulty.GOLD },
            { criteria: { count: 12 }, difficulty: AchievementDifficulty.PLATINUM },
        ],
    },
    {
        codeName: "short_manga",
        name: "Commitment Issues",
        description: "Awarded for completing manga with less than 5 volumes, because good things come in small packages (or you're just lazy).",
        mediaType: MediaType.MANGA,
        value: 5,
        tiers: [
            { criteria: { count: 2 }, difficulty: AchievementDifficulty.BRONZE },
            { criteria: { count: 3 }, difficulty: AchievementDifficulty.SILVER },
            { criteria: { count: 4 }, difficulty: AchievementDifficulty.GOLD },
            { criteria: { count: 5 }, difficulty: AchievementDifficulty.PLATINUM },
        ],
    },
    {
        codeName: "long_manga",
        name: "Marathon Masochist",
        description: "Awarded for completing manga with more than 50 volumes, because who needs sleep when you have 1000+ chapters to read?",
        mediaType: MediaType.MANGA,
        value: 50,
        tiers: [
            { criteria: { count: 1 }, difficulty: AchievementDifficulty.BRONZE },
            { criteria: { count: 2 }, difficulty: AchievementDifficulty.SILVER },
            { criteria: { count: 3 }, difficulty: AchievementDifficulty.GOLD },
            { criteria: { count: 4 }, difficulty: AchievementDifficulty.PLATINUM },
        ],
    },
    {
        codeName: "chapter_manga",
        name: "Page Turner Pro",
        description: "Awarded for reading LOTS of manga chapters, because who needs vitamin D when you have manga?",
        mediaType: MediaType.MANGA,
        tiers: [
            { criteria: { count: 100 }, difficulty: AchievementDifficulty.BRONZE },
            { criteria: { count: 500 }, difficulty: AchievementDifficulty.SILVER },
            { criteria: { count: 1000 }, difficulty: AchievementDifficulty.GOLD },
            { criteria: { count: 5000 }, difficulty: AchievementDifficulty.PLATINUM },
        ],
    },
    {
        codeName: "hentai_manga",
        name: "Yamete Senpai",
        description: "Awarded for completing hentai manga, because 'I read it for the plot' needed its own achievement.",
        mediaType: MediaType.MANGA,
        value: "Hentai",
        tiers: [
            { criteria: { count: 1 }, difficulty: AchievementDifficulty.BRONZE },
            { criteria: { count: 2 }, difficulty: AchievementDifficulty.SILVER },
            { criteria: { count: 3 }, difficulty: AchievementDifficulty.GOLD },
            { criteria: { count: 4 }, difficulty: AchievementDifficulty.PLATINUM },
        ],
    },
    {
        codeName: "shounen_manga",
        name: "Power of Friendship",
        description: "Awarded for completing shounen manga, because screaming makes you stronger and that's just science.",
        mediaType: MediaType.MANGA,
        value: "Shounen",
        tiers: [
            { criteria: { count: 3 }, difficulty: AchievementDifficulty.BRONZE },
            { criteria: { count: 6 }, difficulty: AchievementDifficulty.SILVER },
            { criteria: { count: 9 }, difficulty: AchievementDifficulty.GOLD },
            { criteria: { count: 15 }, difficulty: AchievementDifficulty.PLATINUM },
        ],
    },
    {
        codeName: "seinen_manga",
        name: "Sophisticated Weeb",
        description: "Awarded for completing seinen manga, because reading about existential crises makes you mature.",
        mediaType: MediaType.MANGA,
        value: "Seinen",
        tiers: [
            { criteria: { count: 2 }, difficulty: AchievementDifficulty.BRONZE },
            { criteria: { count: 4 }, difficulty: AchievementDifficulty.SILVER },
            { criteria: { count: 6 }, difficulty: AchievementDifficulty.GOLD },
            { criteria: { count: 8 }, difficulty: AchievementDifficulty.PLATINUM },
        ],
    },
] as const;
