import dedent from "dedent";
import type {CompId, ComponentDefinition, MediaTypeConfig} from "@/lib/client/social-card/types";
import {BookOpen, Calendar, Clock, Computer, Drama, Heart, MessageCircle, Play, RectangleHorizontal, RectangleVertical, Star, TrendingUp, Tv, User} from "lucide-react";


const mediaCountName = (config: MediaTypeConfig) => dedent`
    ${config.terminology.plural.charAt(0).toUpperCase()}${config.terminology.plural.slice(1)}
    ${config.terminology.verbPast.charAt(0).toUpperCase()}${config.terminology.verbPast.slice(1)}
`;


const timeSpentName = (c: MediaTypeConfig) => c.terminology.timeLabel;


export const COMPONENT_DEFS: Record<CompId, ComponentDefinition> = {
    mediaCount: {
        icon: Play,
        mode: "auto",
        id: "mediaCount",
        name: "Media Count",
        defaultLayout: "1x1",
        supportedMedia: "all",
        getDisplayName: mediaCountName,
        availableLayouts: ["1x1"],
    },
    avgRating: {
        icon: Star,
        mode: "auto",
        id: "avgRating",
        name: "Avg. Rating",
        defaultLayout: "1x1",
        supportedMedia: "all",
        availableLayouts: ["1x1"],
    },
    timeSpent: {
        icon: Clock,
        mode: "auto",
        id: "timeSpent",
        name: "Time Spent",
        defaultLayout: "1x1",
        availableLayouts: ["1x1"],
        getDisplayName: timeSpentName,
        supportedMedia: ["movies", "series", "anime", "games"],
    },
    favorites: {
        icon: Heart,
        mode: "auto",
        id: "favorites",
        name: "Favorites",
        defaultLayout: "1x1",
        supportedMedia: "all",
        availableLayouts: ["1x1"],
    },
    activity: {
        mode: "auto",
        id: "activity",
        name: "Activity",
        icon: TrendingUp,
        defaultLayout: "1x1",
        supportedMedia: "all",
        availableLayouts: ["1x1"],
    },
    comments: {
        mode: "auto",
        id: "comments",
        name: "Comments",
        icon: MessageCircle,
        defaultLayout: "1x1",
        supportedMedia: "all",
        availableLayouts: ["1x1"],
    },
    topGenre: {
        icon: Drama,
        mode: "auto",
        id: "topGenre",
        name: "Top Genre",
        defaultLayout: "2x1",
        supportedMedia: "all",
        availableLayouts: ["1x1", "2x1"],
    },
    topActor: {
        icon: User,
        mode: "auto",
        id: "topActor",
        name: "Top Actor",
        defaultLayout: "2x1",
        availableLayouts: ["1x1", "2x1"],
        supportedMedia: ["movies", "series", "anime"],
    },
    topDirector: {
        icon: User,
        mode: "auto",
        id: "topDirector",
        name: "Top Director",
        defaultLayout: "2x1",
        availableLayouts: ["1x1", "2x1"],
        supportedMedia: ["movies", "series"],
    },
    topAuthor: {
        icon: User,
        mode: "auto",
        id: "topAuthor",
        name: "Top Author",
        defaultLayout: "2x1",
        availableLayouts: ["1x1", "2x1"],
        supportedMedia: ["books", "manga"],
    },
    topDeveloper: {
        icon: User,
        mode: "auto",
        id: "topDeveloper",
        defaultLayout: "2x1",
        name: "Top Developer",
        supportedMedia: ["games"],
        availableLayouts: ["1x1", "2x1"],
    },
    topPlatform: {
        mode: "auto",
        icon: Computer,
        id: "topPlatform",
        name: "Top Platform",
        defaultLayout: "2x1",
        supportedMedia: ["games"],
        availableLayouts: ["1x1", "2x1"],
    },
    episodesWatched: {
        icon: Tv,
        mode: "auto",
        defaultLayout: "1x1",
        id: "episodesWatched",
        name: "Episodes Watched",
        availableLayouts: ["1x1"],
        supportedMedia: ["series", "anime"],
    },
    pagesRead: {
        mode: "auto",
        icon: BookOpen,
        id: "pagesRead",
        name: "Pages Read",
        defaultLayout: "1x1",
        supportedMedia: ["books"],
        availableLayouts: ["1x1"],
    },
    chaptersRead: {
        mode: "auto",
        icon: BookOpen,
        id: "chaptersRead",
        defaultLayout: "1x1",
        name: "Chapters Read",
        supportedMedia: ["manga"],
        availableLayouts: ["1x1"],
    },
    featuredMedia: {
        mode: "manual",
        name: "Featured",
        id: "featuredMedia",
        defaultLayout: "1x2",
        supportedMedia: "all",
        icon: RectangleVertical,
        availableLayouts: ["1x2"],
        getDisplayName: (c) => `Featured ${c.terminology.singular}`,
    },
    mediaShowcase: {
        mode: "manual",
        name: "Showcase",
        id: "mediaShowcase",
        defaultLayout: "4x2",
        supportedMedia: "all",
        availableLayouts: ["4x2"],
        icon: RectangleHorizontal,
        getDisplayName: (c) => `${c.terminology.plural.charAt(0).toUpperCase()}${c.terminology.plural.slice(1)} Showcase`,
    },
    yearInReview: {
        mode: "auto",
        icon: Calendar,
        id: "yearInReview",
        defaultLayout: "4x1",
        supportedMedia: "all",
        name: "Year in Review",
        availableLayouts: ["4x1"],
    },
};
