import {MediaType} from "@/lib/utils/enums";
import {getMediaIcon} from "@/lib/utils/functions";
import {MediaTypeConfig} from "@/lib/client/social-card/types";


export const MEDIA_CONFIGS: Record<MediaType | "user", MediaTypeConfig> = {
    series: {
        id: "series",
        name: "Series",
        hasEpisodes: true,
        icon: getMediaIcon(MediaType.SERIES),
        terminology: {
            plural: "series",
            timeUnit: "hours",
            singular: "series",
            verbPast: "watched",
            verbPresent: "watch",
            ratingLabel: "Rating",
            timeLabel: "Watch Time",
            timeUnitSingular: "hour",
        },
        availableComps: [
            "activity",
            "comments",
            "topGenre",
            "topActor",
            "avgRating",
            "timeSpent",
            "favorites",
            "mediaCount",
            "topDirector",
            "yearInReview",
            "featuredMedia",
            "mediaShowcase",
            "episodesWatched",
        ],
        defaultLayout: [
            { compId: "yearInReview", layout: "4x1" },
            { compId: "episodesWatched", layout: "1x1" },
            { compId: "topGenre", layout: "2x1" },
            { compId: "activity", layout: "1x1" },
        ],
    },
    anime: {
        id: "anime",
        name: "Anime",
        icon: getMediaIcon(MediaType.ANIME),
        hasEpisodes: true,
        terminology: {
            singular: "anime",
            plural: "anime",
            verbPresent: "watch",
            verbPast: "watched",
            timeUnit: "hours",
            timeUnitSingular: "hour",
            timeLabel: "Watch Time",
            ratingLabel: "Score",
        },
        availableComps: [
            "mediaCount",
            "avgRating",
            "timeSpent",
            "favorites",
            "activity",
            "comments",
            "topGenre",
            "episodesWatched",
            "featuredMedia",
            "mediaShowcase",
            "yearInReview",
        ],
        defaultLayout: [
            { compId: "yearInReview", layout: "4x1" },
            { compId: "episodesWatched", layout: "1x1" },
            { compId: "topGenre", layout: "2x1" },
            { compId: "activity", layout: "1x1" },
        ],
    },
    movies: {
        id: "movies",
        name: "Movies",
        icon: getMediaIcon(MediaType.MOVIES),
        terminology: {
            plural: "movies",
            timeUnit: "hours",
            singular: "movie",
            verbPast: "watched",
            verbPresent: "watch",
            ratingLabel: "Rating",
            timeLabel: "Watch Time",
            timeUnitSingular: "hour",
        },
        availableComps: [
            "activity",
            "comments",
            "topGenre",
            "topActor",
            "avgRating",
            "timeSpent",
            "favorites",
            "mediaCount",
            "topDirector",
            "yearInReview",
            "featuredMedia",
            "mediaShowcase",
        ],
        defaultLayout: [
            { compId: "yearInReview", layout: "4x1" },
            { compId: "topDirector", layout: "2x1" },
            { compId: "topGenre", layout: "2x1" },
        ],
    },
    games: {
        id: "games",
        name: "Games",
        icon: getMediaIcon(MediaType.GAMES),
        terminology: {
            plural: "games",
            singular: "game",
            timeUnit: "hours",
            verbPast: "played",
            verbPresent: "play",
            ratingLabel: "Rating",
            timeLabel: "Playtime",
            timeUnitSingular: "hour",
        },
        availableComps: [
            "activity",
            "comments",
            "topGenre",
            "avgRating",
            "timeSpent",
            "favorites",
            "mediaCount",
            "topPlatform",
            "topDeveloper",
            "yearInReview",
            "featuredMedia",
            "mediaShowcase",
        ],
        defaultLayout: [
            { compId: "yearInReview", layout: "4x1" },
            { compId: "topPlatform", layout: "1x1" },
            { compId: "topDeveloper", layout: "2x1" },
            { compId: "activity", layout: "1x1" },
        ],
    },
    books: {
        id: "books",
        name: "Books",
        icon: getMediaIcon(MediaType.BOOKS),
        hasPages: true,
        terminology: {
            plural: "books",
            singular: "book",
            verbPast: "read",
            timeUnit: "pages",
            verbPresent: "read",
            ratingLabel: "Rating",
            timeLabel: "Pages Read",
            timeUnitSingular: "page",
        },
        availableComps: [
            "activity",
            "comments",
            "topGenre",
            "avgRating",
            "pagesRead",
            "favorites",
            "topAuthor",
            "mediaCount",
            "yearInReview",
            "featuredMedia",
            "mediaShowcase",
        ],
        defaultLayout: [
            { compId: "yearInReview", layout: "4x1" },
            { compId: "topAuthor", layout: "2x1" },
            { compId: "topGenre", layout: "2x1" },
        ],
    },
    manga: {
        id: "manga",
        name: "Manga",
        icon: getMediaIcon(MediaType.MANGA),
        hasChapters: true,
        terminology: {
            plural: "manga",
            verbPast: "read",
            singular: "manga",
            verbPresent: "read",
            timeUnit: "chapters",
            ratingLabel: "Score",
            timeLabel: "Chapters Read",
            timeUnitSingular: "chapter",
        },
        availableComps: [
            "activity",
            "comments",
            "topGenre",
            "avgRating",
            "favorites",
            "topAuthor",
            "mediaCount",
            "chaptersRead",
            "yearInReview",
            "featuredMedia",
            "mediaShowcase",
        ],
        defaultLayout: [
            { compId: "yearInReview", layout: "4x1" },
            { compId: "topAuthor", layout: "2x1" },
            { compId: "topGenre", layout: "2x1" },
        ],
    },
    user: {
        id: "user",
        name: "Profile",
        icon: getMediaIcon("user"),
        terminology: {
            plural: "items",
            singular: "item",
            timeUnit: "hours",
            verbPast: "tracked",
            verbPresent: "track",
            ratingLabel: "Rating",
            timeLabel: "Time Spent",
            timeUnitSingular: "hour",
        },
        availableComps: [
            "activity",
            "comments",
            "avgRating",
            "timeSpent",
            "favorites",
            "mediaCount",
            "featuredMedia",
            "mediaShowcase",
        ],
        defaultLayout: [
            { compId: "mediaCount", layout: "1x1" },
            { compId: "timeSpent", layout: "1x1" },
            { compId: "favorites", layout: "1x1" },
            { compId: "activity", layout: "1x1" },
            { compId: "mediaShowcase", layout: "4x2" },
        ],
    },
};


export const getAccentClasses = (mediaType: MediaType | "user") => {
    const colors: Record<MediaType | "user", { text: string; bg: string; border: string }> = {
        series: {
            bg: "bg-series",
            text: "text-series",
            border: "border-series",
        },
        anime: {
            bg: "bg-anime",
            text: "text-anime",
            border: "border-anime",
        },
        movies: {
            bg: "bg-movies",
            text: "text-movies",
            border: "border-movies",
        },
        games: {
            bg: "bg-games",
            text: "text-games",
            border: "border-games",
        },
        books: {
            bg: "bg-books",
            text: "text-books",
            border: "border-books",
        },
        manga: {
            bg: "bg-manga",
            text: "text-manga",
            border: "border-manga",
        },
        user: {
            bg: "bg-user",
            text: "text-user",
            border: "border-user",
        },
    };

    return colors[mediaType];
};
