/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UniversalImport } from './routes/_universal'
import { Route as PublicImport } from './routes/_public'
import { Route as PrivateImport } from './routes/_private'
import { Route as PublicIndexImport } from './routes/_public/index'
import { Route as UniversalPrivacypolicyImport } from './routes/_universal/privacy_policy'
import { Route as UniversalAboutImport } from './routes/_universal/about'
import { Route as PublicResetpasswordImport } from './routes/_public/reset_password'
import { Route as PublicRegistertokenImport } from './routes/_public/register_token'
import { Route as PublicForgotpasswordImport } from './routes/_public/forgot_password'
import { Route as PrivateTrendsImport } from './routes/_private/trends'
import { Route as PrivateSettingsImport } from './routes/_private/settings'
import { Route as PrivateHalloffameImport } from './routes/_private/hall_of_fame'
import { Route as PrivateGlobalstatsImport } from './routes/_private/global_stats'
import { Route as PrivateComingnextImport } from './routes/_private/coming_next'
import { Route as PrivateAdminIndexImport } from './routes/_private/admin/index'
import { Route as UniversalLevelsProfilelevelsImport } from './routes/_universal/levels.profile_levels'
import { Route as UniversalLevelsMedialevelsImport } from './routes/_universal/levels.media_levels'
import { Route as PrivateAdminDashboardImport } from './routes/_private/admin/dashboard'
import { Route as PublicOauth2ProviderCallbackImport } from './routes/_public/oauth2.$provider.callback'
import { Route as PrivateStatsMediaTypeUsernameImport } from './routes/_private/stats/$mediaType.$username'
import { Route as PrivateProfileUsernameHeaderImport } from './routes/_private/profile/$username/_header'
import { Route as PrivateListMediaTypeUsernameImport } from './routes/_private/list/$mediaType.$username'
import { Route as PrivateDetailsMediaTypeMediaIdImport } from './routes/_private/details/$mediaType.$mediaId'
import { Route as PrivateProfileUsernameHeaderIndexImport } from './routes/_private/profile/$username/_header/index'
import { Route as PrivateProfileUsernameHeaderHistoryImport } from './routes/_private/profile/$username/_header/history'
import { Route as PrivateProfileUsernameHeaderFollowsImport } from './routes/_private/profile/$username/_header/follows'
import { Route as PrivateProfileUsernameHeaderFollowersImport } from './routes/_private/profile/$username/_header/followers'
import { Route as PrivateDetailsFormMediaTypeMediaIdImport } from './routes/_private/details/form.$mediaType.$mediaId'
import { Route as PrivateDetailsMediaTypeJobInfoImport } from './routes/_private/details/$mediaType.$job.$info'

// Create Virtual Routes

const PrivateProfileUsernameImport = createFileRoute(
  '/_private/profile/$username',
)()

// Create/Update Routes

const UniversalRoute = UniversalImport.update({
  id: '/_universal',
  getParentRoute: () => rootRoute,
} as any)

const PublicRoute = PublicImport.update({
  id: '/_public',
  getParentRoute: () => rootRoute,
} as any)

const PrivateRoute = PrivateImport.update({
  id: '/_private',
  getParentRoute: () => rootRoute,
} as any)

const PublicIndexRoute = PublicIndexImport.update({
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)

const UniversalPrivacypolicyRoute = UniversalPrivacypolicyImport.update({
  path: '/privacy_policy',
  getParentRoute: () => UniversalRoute,
} as any)

const UniversalAboutRoute = UniversalAboutImport.update({
  path: '/about',
  getParentRoute: () => UniversalRoute,
} as any)

const PublicResetpasswordRoute = PublicResetpasswordImport.update({
  path: '/reset_password',
  getParentRoute: () => PublicRoute,
} as any)

const PublicRegistertokenRoute = PublicRegistertokenImport.update({
  path: '/register_token',
  getParentRoute: () => PublicRoute,
} as any)

const PublicForgotpasswordRoute = PublicForgotpasswordImport.update({
  path: '/forgot_password',
  getParentRoute: () => PublicRoute,
} as any)

const PrivateTrendsRoute = PrivateTrendsImport.update({
  path: '/trends',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateSettingsRoute = PrivateSettingsImport.update({
  path: '/settings',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateHalloffameRoute = PrivateHalloffameImport.update({
  path: '/hall_of_fame',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateGlobalstatsRoute = PrivateGlobalstatsImport.update({
  path: '/global_stats',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateComingnextRoute = PrivateComingnextImport.update({
  path: '/coming_next',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateProfileUsernameRoute = PrivateProfileUsernameImport.update({
  path: '/profile/$username',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateAdminIndexRoute = PrivateAdminIndexImport.update({
  path: '/admin/',
  getParentRoute: () => PrivateRoute,
} as any)

const UniversalLevelsProfilelevelsRoute =
  UniversalLevelsProfilelevelsImport.update({
    path: '/levels/profile_levels',
    getParentRoute: () => UniversalRoute,
  } as any)

const UniversalLevelsMedialevelsRoute = UniversalLevelsMedialevelsImport.update(
  {
    path: '/levels/media_levels',
    getParentRoute: () => UniversalRoute,
  } as any,
)

const PrivateAdminDashboardRoute = PrivateAdminDashboardImport.update({
  path: '/admin/dashboard',
  getParentRoute: () => PrivateRoute,
} as any)

const PublicOauth2ProviderCallbackRoute =
  PublicOauth2ProviderCallbackImport.update({
    path: '/oauth2/$provider/callback',
    getParentRoute: () => PublicRoute,
  } as any)

const PrivateStatsMediaTypeUsernameRoute =
  PrivateStatsMediaTypeUsernameImport.update({
    path: '/stats/$mediaType/$username',
    getParentRoute: () => PrivateRoute,
  } as any)

const PrivateProfileUsernameHeaderRoute =
  PrivateProfileUsernameHeaderImport.update({
    id: '/_header',
    getParentRoute: () => PrivateProfileUsernameRoute,
  } as any)

const PrivateListMediaTypeUsernameRoute =
  PrivateListMediaTypeUsernameImport.update({
    path: '/list/$mediaType/$username',
    getParentRoute: () => PrivateRoute,
  } as any)

const PrivateDetailsMediaTypeMediaIdRoute =
  PrivateDetailsMediaTypeMediaIdImport.update({
    path: '/details/$mediaType/$mediaId',
    getParentRoute: () => PrivateRoute,
  } as any)

const PrivateProfileUsernameHeaderIndexRoute =
  PrivateProfileUsernameHeaderIndexImport.update({
    path: '/',
    getParentRoute: () => PrivateProfileUsernameHeaderRoute,
  } as any)

const PrivateProfileUsernameHeaderHistoryRoute =
  PrivateProfileUsernameHeaderHistoryImport.update({
    path: '/history',
    getParentRoute: () => PrivateProfileUsernameHeaderRoute,
  } as any)

const PrivateProfileUsernameHeaderFollowsRoute =
  PrivateProfileUsernameHeaderFollowsImport.update({
    path: '/follows',
    getParentRoute: () => PrivateProfileUsernameHeaderRoute,
  } as any)

const PrivateProfileUsernameHeaderFollowersRoute =
  PrivateProfileUsernameHeaderFollowersImport.update({
    path: '/followers',
    getParentRoute: () => PrivateProfileUsernameHeaderRoute,
  } as any)

const PrivateDetailsFormMediaTypeMediaIdRoute =
  PrivateDetailsFormMediaTypeMediaIdImport.update({
    path: '/details/form/$mediaType/$mediaId',
    getParentRoute: () => PrivateRoute,
  } as any)

const PrivateDetailsMediaTypeJobInfoRoute =
  PrivateDetailsMediaTypeJobInfoImport.update({
    path: '/details/$mediaType/$job/$info',
    getParentRoute: () => PrivateRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      preLoaderRoute: typeof PrivateImport
      parentRoute: typeof rootRoute
    }
    '/_public': {
      preLoaderRoute: typeof PublicImport
      parentRoute: typeof rootRoute
    }
    '/_universal': {
      preLoaderRoute: typeof UniversalImport
      parentRoute: typeof rootRoute
    }
    '/_private/coming_next': {
      preLoaderRoute: typeof PrivateComingnextImport
      parentRoute: typeof PrivateImport
    }
    '/_private/global_stats': {
      preLoaderRoute: typeof PrivateGlobalstatsImport
      parentRoute: typeof PrivateImport
    }
    '/_private/hall_of_fame': {
      preLoaderRoute: typeof PrivateHalloffameImport
      parentRoute: typeof PrivateImport
    }
    '/_private/settings': {
      preLoaderRoute: typeof PrivateSettingsImport
      parentRoute: typeof PrivateImport
    }
    '/_private/trends': {
      preLoaderRoute: typeof PrivateTrendsImport
      parentRoute: typeof PrivateImport
    }
    '/_public/forgot_password': {
      preLoaderRoute: typeof PublicForgotpasswordImport
      parentRoute: typeof PublicImport
    }
    '/_public/register_token': {
      preLoaderRoute: typeof PublicRegistertokenImport
      parentRoute: typeof PublicImport
    }
    '/_public/reset_password': {
      preLoaderRoute: typeof PublicResetpasswordImport
      parentRoute: typeof PublicImport
    }
    '/_universal/about': {
      preLoaderRoute: typeof UniversalAboutImport
      parentRoute: typeof UniversalImport
    }
    '/_universal/privacy_policy': {
      preLoaderRoute: typeof UniversalPrivacypolicyImport
      parentRoute: typeof UniversalImport
    }
    '/_public/': {
      preLoaderRoute: typeof PublicIndexImport
      parentRoute: typeof PublicImport
    }
    '/_private/admin/dashboard': {
      preLoaderRoute: typeof PrivateAdminDashboardImport
      parentRoute: typeof PrivateImport
    }
    '/_universal/levels/media_levels': {
      preLoaderRoute: typeof UniversalLevelsMedialevelsImport
      parentRoute: typeof UniversalImport
    }
    '/_universal/levels/profile_levels': {
      preLoaderRoute: typeof UniversalLevelsProfilelevelsImport
      parentRoute: typeof UniversalImport
    }
    '/_private/admin/': {
      preLoaderRoute: typeof PrivateAdminIndexImport
      parentRoute: typeof PrivateImport
    }
    '/_private/details/$mediaType/$mediaId': {
      preLoaderRoute: typeof PrivateDetailsMediaTypeMediaIdImport
      parentRoute: typeof PrivateImport
    }
    '/_private/list/$mediaType/$username': {
      preLoaderRoute: typeof PrivateListMediaTypeUsernameImport
      parentRoute: typeof PrivateImport
    }
    '/_private/profile/$username': {
      preLoaderRoute: typeof PrivateProfileUsernameImport
      parentRoute: typeof PrivateImport
    }
    '/_private/profile/$username/_header': {
      preLoaderRoute: typeof PrivateProfileUsernameHeaderImport
      parentRoute: typeof PrivateProfileUsernameRoute
    }
    '/_private/stats/$mediaType/$username': {
      preLoaderRoute: typeof PrivateStatsMediaTypeUsernameImport
      parentRoute: typeof PrivateImport
    }
    '/_public/oauth2/$provider/callback': {
      preLoaderRoute: typeof PublicOauth2ProviderCallbackImport
      parentRoute: typeof PublicImport
    }
    '/_private/details/$mediaType/$job/$info': {
      preLoaderRoute: typeof PrivateDetailsMediaTypeJobInfoImport
      parentRoute: typeof PrivateImport
    }
    '/_private/details/form/$mediaType/$mediaId': {
      preLoaderRoute: typeof PrivateDetailsFormMediaTypeMediaIdImport
      parentRoute: typeof PrivateImport
    }
    '/_private/profile/$username/_header/followers': {
      preLoaderRoute: typeof PrivateProfileUsernameHeaderFollowersImport
      parentRoute: typeof PrivateProfileUsernameHeaderImport
    }
    '/_private/profile/$username/_header/follows': {
      preLoaderRoute: typeof PrivateProfileUsernameHeaderFollowsImport
      parentRoute: typeof PrivateProfileUsernameHeaderImport
    }
    '/_private/profile/$username/_header/history': {
      preLoaderRoute: typeof PrivateProfileUsernameHeaderHistoryImport
      parentRoute: typeof PrivateProfileUsernameHeaderImport
    }
    '/_private/profile/$username/_header/': {
      preLoaderRoute: typeof PrivateProfileUsernameHeaderIndexImport
      parentRoute: typeof PrivateProfileUsernameHeaderImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  PrivateRoute.addChildren([
    PrivateComingnextRoute,
    PrivateGlobalstatsRoute,
    PrivateHalloffameRoute,
    PrivateSettingsRoute,
    PrivateTrendsRoute,
    PrivateAdminDashboardRoute,
    PrivateAdminIndexRoute,
    PrivateDetailsMediaTypeMediaIdRoute,
    PrivateListMediaTypeUsernameRoute,
    PrivateProfileUsernameRoute.addChildren([
      PrivateProfileUsernameHeaderRoute.addChildren([
        PrivateProfileUsernameHeaderFollowersRoute,
        PrivateProfileUsernameHeaderFollowsRoute,
        PrivateProfileUsernameHeaderHistoryRoute,
        PrivateProfileUsernameHeaderIndexRoute,
      ]),
    ]),
    PrivateStatsMediaTypeUsernameRoute,
    PrivateDetailsMediaTypeJobInfoRoute,
    PrivateDetailsFormMediaTypeMediaIdRoute,
  ]),
  PublicRoute.addChildren([
    PublicForgotpasswordRoute,
    PublicRegistertokenRoute,
    PublicResetpasswordRoute,
    PublicIndexRoute,
    PublicOauth2ProviderCallbackRoute,
  ]),
  UniversalRoute.addChildren([
    UniversalAboutRoute,
    UniversalPrivacypolicyRoute,
    UniversalLevelsMedialevelsRoute,
    UniversalLevelsProfilelevelsRoute,
  ]),
])

/* prettier-ignore-end */
