/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PublicImport } from './routes/_public'
import { Route as PrivateImport } from './routes/_private'
import { Route as PublicIndexImport } from './routes/_public/index'
import { Route as UniversalPrivacyPolicyImport } from './routes/_universal/privacy-policy'
import { Route as UniversalFeaturesImport } from './routes/_universal/features'
import { Route as UniversalAboutImport } from './routes/_universal/about'
import { Route as PublicForgotPasswordImport } from './routes/_public/forgot-password'
import { Route as PrivateProfileUsernameHeaderImport } from './routes/_private/profile/$username/_header'
import { Route as PrivateDetailsMediaTypeMediaIdImport } from './routes/_private/details/$mediaType/$mediaId'
import { Route as PrivateListMediaTypeUsernameRouteImport } from './routes/_private/list/$mediaType/$username.route'
import { Route as PrivateProfileUsernameHeaderIndexImport } from './routes/_private/profile/$username/_header/index'
import { Route as PrivateProfileUsernameHeaderFollowersImport } from './routes/_private/profile/$username/_header/followers'

// Create Virtual Routes

const PrivateProfileUsernameImport = createFileRoute(
  '/_private/profile/$username',
)()

// Create/Update Routes

const PublicRoute = PublicImport.update({
  id: '/_public',
  getParentRoute: () => rootRoute,
} as any)

const PrivateRoute = PrivateImport.update({
  id: '/_private',
  getParentRoute: () => rootRoute,
} as any)

const PublicIndexRoute = PublicIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)

const UniversalPrivacyPolicyRoute = UniversalPrivacyPolicyImport.update({
  id: '/_universal/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRoute,
} as any)

const UniversalFeaturesRoute = UniversalFeaturesImport.update({
  id: '/_universal/features',
  path: '/features',
  getParentRoute: () => rootRoute,
} as any)

const UniversalAboutRoute = UniversalAboutImport.update({
  id: '/_universal/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const PublicForgotPasswordRoute = PublicForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PublicRoute,
} as any)

const PrivateProfileUsernameRoute = PrivateProfileUsernameImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateProfileUsernameHeaderRoute =
  PrivateProfileUsernameHeaderImport.update({
    id: '/_header',
    getParentRoute: () => PrivateProfileUsernameRoute,
  } as any)

const PrivateDetailsMediaTypeMediaIdRoute =
  PrivateDetailsMediaTypeMediaIdImport.update({
    id: '/details/$mediaType/$mediaId',
    path: '/details/$mediaType/$mediaId',
    getParentRoute: () => PrivateRoute,
  } as any)

const PrivateListMediaTypeUsernameRouteRoute =
  PrivateListMediaTypeUsernameRouteImport.update({
    id: '/list/$mediaType/$username',
    path: '/list/$mediaType/$username',
    getParentRoute: () => PrivateRoute,
  } as any)

const PrivateProfileUsernameHeaderIndexRoute =
  PrivateProfileUsernameHeaderIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrivateProfileUsernameHeaderRoute,
  } as any)

const PrivateProfileUsernameHeaderFollowersRoute =
  PrivateProfileUsernameHeaderFollowersImport.update({
    id: '/followers',
    path: '/followers',
    getParentRoute: () => PrivateProfileUsernameHeaderRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateImport
      parentRoute: typeof rootRoute
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicImport
      parentRoute: typeof rootRoute
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordImport
      parentRoute: typeof PublicImport
    }
    '/_universal/about': {
      id: '/_universal/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof UniversalAboutImport
      parentRoute: typeof rootRoute
    }
    '/_universal/features': {
      id: '/_universal/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof UniversalFeaturesImport
      parentRoute: typeof rootRoute
    }
    '/_universal/privacy-policy': {
      id: '/_universal/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof UniversalPrivacyPolicyImport
      parentRoute: typeof rootRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexImport
      parentRoute: typeof PublicImport
    }
    '/_private/list/$mediaType/$username': {
      id: '/_private/list/$mediaType/$username'
      path: '/list/$mediaType/$username'
      fullPath: '/list/$mediaType/$username'
      preLoaderRoute: typeof PrivateListMediaTypeUsernameRouteImport
      parentRoute: typeof PrivateImport
    }
    '/_private/details/$mediaType/$mediaId': {
      id: '/_private/details/$mediaType/$mediaId'
      path: '/details/$mediaType/$mediaId'
      fullPath: '/details/$mediaType/$mediaId'
      preLoaderRoute: typeof PrivateDetailsMediaTypeMediaIdImport
      parentRoute: typeof PrivateImport
    }
    '/_private/profile/$username': {
      id: '/_private/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof PrivateProfileUsernameImport
      parentRoute: typeof PrivateImport
    }
    '/_private/profile/$username/_header': {
      id: '/_private/profile/$username/_header'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof PrivateProfileUsernameHeaderImport
      parentRoute: typeof PrivateProfileUsernameRoute
    }
    '/_private/profile/$username/_header/followers': {
      id: '/_private/profile/$username/_header/followers'
      path: '/followers'
      fullPath: '/profile/$username/followers'
      preLoaderRoute: typeof PrivateProfileUsernameHeaderFollowersImport
      parentRoute: typeof PrivateProfileUsernameHeaderImport
    }
    '/_private/profile/$username/_header/': {
      id: '/_private/profile/$username/_header/'
      path: '/'
      fullPath: '/profile/$username/'
      preLoaderRoute: typeof PrivateProfileUsernameHeaderIndexImport
      parentRoute: typeof PrivateProfileUsernameHeaderImport
    }
  }
}

// Create and export the route tree

interface PrivateProfileUsernameHeaderRouteChildren {
  PrivateProfileUsernameHeaderFollowersRoute: typeof PrivateProfileUsernameHeaderFollowersRoute
  PrivateProfileUsernameHeaderIndexRoute: typeof PrivateProfileUsernameHeaderIndexRoute
}

const PrivateProfileUsernameHeaderRouteChildren: PrivateProfileUsernameHeaderRouteChildren =
  {
    PrivateProfileUsernameHeaderFollowersRoute:
      PrivateProfileUsernameHeaderFollowersRoute,
    PrivateProfileUsernameHeaderIndexRoute:
      PrivateProfileUsernameHeaderIndexRoute,
  }

const PrivateProfileUsernameHeaderRouteWithChildren =
  PrivateProfileUsernameHeaderRoute._addFileChildren(
    PrivateProfileUsernameHeaderRouteChildren,
  )

interface PrivateProfileUsernameRouteChildren {
  PrivateProfileUsernameHeaderRoute: typeof PrivateProfileUsernameHeaderRouteWithChildren
}

const PrivateProfileUsernameRouteChildren: PrivateProfileUsernameRouteChildren =
  {
    PrivateProfileUsernameHeaderRoute:
      PrivateProfileUsernameHeaderRouteWithChildren,
  }

const PrivateProfileUsernameRouteWithChildren =
  PrivateProfileUsernameRoute._addFileChildren(
    PrivateProfileUsernameRouteChildren,
  )

interface PrivateRouteChildren {
  PrivateListMediaTypeUsernameRouteRoute: typeof PrivateListMediaTypeUsernameRouteRoute
  PrivateDetailsMediaTypeMediaIdRoute: typeof PrivateDetailsMediaTypeMediaIdRoute
  PrivateProfileUsernameRoute: typeof PrivateProfileUsernameRouteWithChildren
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateListMediaTypeUsernameRouteRoute:
    PrivateListMediaTypeUsernameRouteRoute,
  PrivateDetailsMediaTypeMediaIdRoute: PrivateDetailsMediaTypeMediaIdRoute,
  PrivateProfileUsernameRoute: PrivateProfileUsernameRouteWithChildren,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface PublicRouteChildren {
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof PublicRouteWithChildren
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/about': typeof UniversalAboutRoute
  '/features': typeof UniversalFeaturesRoute
  '/privacy-policy': typeof UniversalPrivacyPolicyRoute
  '/': typeof PublicIndexRoute
  '/list/$mediaType/$username': typeof PrivateListMediaTypeUsernameRouteRoute
  '/details/$mediaType/$mediaId': typeof PrivateDetailsMediaTypeMediaIdRoute
  '/profile/$username': typeof PrivateProfileUsernameHeaderRouteWithChildren
  '/profile/$username/followers': typeof PrivateProfileUsernameHeaderFollowersRoute
  '/profile/$username/': typeof PrivateProfileUsernameHeaderIndexRoute
}

export interface FileRoutesByTo {
  '': typeof PrivateRouteWithChildren
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/about': typeof UniversalAboutRoute
  '/features': typeof UniversalFeaturesRoute
  '/privacy-policy': typeof UniversalPrivacyPolicyRoute
  '/': typeof PublicIndexRoute
  '/list/$mediaType/$username': typeof PrivateListMediaTypeUsernameRouteRoute
  '/details/$mediaType/$mediaId': typeof PrivateDetailsMediaTypeMediaIdRoute
  '/profile/$username': typeof PrivateProfileUsernameHeaderIndexRoute
  '/profile/$username/followers': typeof PrivateProfileUsernameHeaderFollowersRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_private': typeof PrivateRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_public/forgot-password': typeof PublicForgotPasswordRoute
  '/_universal/about': typeof UniversalAboutRoute
  '/_universal/features': typeof UniversalFeaturesRoute
  '/_universal/privacy-policy': typeof UniversalPrivacyPolicyRoute
  '/_public/': typeof PublicIndexRoute
  '/_private/list/$mediaType/$username': typeof PrivateListMediaTypeUsernameRouteRoute
  '/_private/details/$mediaType/$mediaId': typeof PrivateDetailsMediaTypeMediaIdRoute
  '/_private/profile/$username': typeof PrivateProfileUsernameRouteWithChildren
  '/_private/profile/$username/_header': typeof PrivateProfileUsernameHeaderRouteWithChildren
  '/_private/profile/$username/_header/followers': typeof PrivateProfileUsernameHeaderFollowersRoute
  '/_private/profile/$username/_header/': typeof PrivateProfileUsernameHeaderIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/forgot-password'
    | '/about'
    | '/features'
    | '/privacy-policy'
    | '/'
    | '/list/$mediaType/$username'
    | '/details/$mediaType/$mediaId'
    | '/profile/$username'
    | '/profile/$username/followers'
    | '/profile/$username/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/forgot-password'
    | '/about'
    | '/features'
    | '/privacy-policy'
    | '/'
    | '/list/$mediaType/$username'
    | '/details/$mediaType/$mediaId'
    | '/profile/$username'
    | '/profile/$username/followers'
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/_public/forgot-password'
    | '/_universal/about'
    | '/_universal/features'
    | '/_universal/privacy-policy'
    | '/_public/'
    | '/_private/list/$mediaType/$username'
    | '/_private/details/$mediaType/$mediaId'
    | '/_private/profile/$username'
    | '/_private/profile/$username/_header'
    | '/_private/profile/$username/_header/followers'
    | '/_private/profile/$username/_header/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  PrivateRoute: typeof PrivateRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  UniversalAboutRoute: typeof UniversalAboutRoute
  UniversalFeaturesRoute: typeof UniversalFeaturesRoute
  UniversalPrivacyPolicyRoute: typeof UniversalPrivacyPolicyRoute
}

const rootRouteChildren: RootRouteChildren = {
  PrivateRoute: PrivateRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  UniversalAboutRoute: UniversalAboutRoute,
  UniversalFeaturesRoute: UniversalFeaturesRoute,
  UniversalPrivacyPolicyRoute: UniversalPrivacyPolicyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_private",
        "/_public",
        "/_universal/about",
        "/_universal/features",
        "/_universal/privacy-policy"
      ]
    },
    "/_private": {
      "filePath": "_private.tsx",
      "children": [
        "/_private/list/$mediaType/$username",
        "/_private/details/$mediaType/$mediaId",
        "/_private/profile/$username"
      ]
    },
    "/_public": {
      "filePath": "_public.tsx",
      "children": [
        "/_public/forgot-password",
        "/_public/"
      ]
    },
    "/_public/forgot-password": {
      "filePath": "_public/forgot-password.tsx",
      "parent": "/_public"
    },
    "/_universal/about": {
      "filePath": "_universal/about.tsx"
    },
    "/_universal/features": {
      "filePath": "_universal/features.tsx"
    },
    "/_universal/privacy-policy": {
      "filePath": "_universal/privacy-policy.tsx"
    },
    "/_public/": {
      "filePath": "_public/index.tsx",
      "parent": "/_public"
    },
    "/_private/list/$mediaType/$username": {
      "filePath": "_private/list/$mediaType/$username.route.tsx",
      "parent": "/_private"
    },
    "/_private/details/$mediaType/$mediaId": {
      "filePath": "_private/details/$mediaType/$mediaId.tsx",
      "parent": "/_private"
    },
    "/_private/profile/$username": {
      "filePath": "_private/profile/$username",
      "parent": "/_private",
      "children": [
        "/_private/profile/$username/_header"
      ]
    },
    "/_private/profile/$username/_header": {
      "filePath": "_private/profile/$username/_header.tsx",
      "parent": "/_private/profile/$username",
      "children": [
        "/_private/profile/$username/_header/followers",
        "/_private/profile/$username/_header/"
      ]
    },
    "/_private/profile/$username/_header/followers": {
      "filePath": "_private/profile/$username/_header/followers.tsx",
      "parent": "/_private/profile/$username/_header"
    },
    "/_private/profile/$username/_header/": {
      "filePath": "_private/profile/$username/_header/index.tsx",
      "parent": "/_private/profile/$username/_header"
    }
  }
}
ROUTE_MANIFEST_END */
