/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router";

import { Route as rootRouteImport } from "./routes/__root";
import { Route as MainRouteImport } from "./routes/_main";
import { Route as AdminRouteImport } from "./routes/_admin";
import { Route as MainPublicRouteImport } from "./routes/_main/_public";
import { Route as MainPrivateRouteImport } from "./routes/_main/_private";
import { Route as MainPublicIndexRouteImport } from "./routes/_main/_public/index";
import { Route as AdminAdminIndexRouteImport } from "./routes/_admin/admin/index";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth/$";
import { Route as MainUniversalPrivacyPolicyRouteImport } from "./routes/_main/_universal/privacy-policy";
import { Route as MainUniversalFeaturesRouteImport } from "./routes/_main/_universal/features";
import { Route as MainUniversalAboutRouteImport } from "./routes/_main/_universal/about";
import { Route as MainPublicResetPasswordRouteImport } from "./routes/_main/_public/reset-password";
import { Route as MainPublicForgotPasswordRouteImport } from "./routes/_main/_public/forgot-password";
import { Route as AdminAdminUsersRouteImport } from "./routes/_admin/admin/users";
import { Route as AdminAdminOverviewRouteImport } from "./routes/_admin/admin/overview";
import { Route as AdminAdminMediadleRouteImport } from "./routes/_admin/admin/mediadle";
import { Route as AdminAdminMediaOverviewRouteImport } from "./routes/_admin/admin/media-overview";
import { Route as AdminAdminErrorLogsRouteImport } from "./routes/_admin/admin/error-logs";
import { Route as AdminAdminArchivedTasksRouteImport } from "./routes/_admin/admin/archived-tasks";
import { Route as AdminAdminAdminTasksRouteImport } from "./routes/_admin/admin/admin-tasks";
import { Route as AdminAdminAchievementsRouteImport } from "./routes/_admin/admin/achievements";
import { Route as MainPrivateTrendsRouteRouteImport } from "./routes/_main/_private/trends/route";
import { Route as MainPrivateSearchRouteRouteImport } from "./routes/_main/_private/search/route";
import { Route as MainPrivatePlatformStatsRouteRouteImport } from "./routes/_main/_private/platform-stats/route";
import { Route as MainPrivateMoviedleRouteRouteImport } from "./routes/_main/_private/moviedle/route";
import { Route as MainPrivateHallOfFameRouteRouteImport } from "./routes/_main/_private/hall-of-fame/route";
import { Route as MainPrivateComingNextRouteRouteImport } from "./routes/_main/_private/coming-next/route";
import { Route as MainPrivateSettingsIndexRouteImport } from "./routes/_main/_private/settings/index";
import { Route as MainPrivateStatsUsernameRouteImport } from "./routes/_main/_private/stats/$username";
import { Route as MainPrivateAchievementsUsernameRouteImport } from "./routes/_main/_private/achievements/$username";
import { Route as MainPrivateProfileUsernameHeaderRouteImport } from "./routes/_main/_private/profile/$username/_header";
import { Route as MainPrivateDetailsMediaTypeMediaIdRouteImport } from "./routes/_main/_private/details/$mediaType/$mediaId";
import { Route as MainPrivateSettingsUploadsTaskIdRouteRouteImport } from "./routes/_main/_private/settings/uploads.$taskId/route";
import { Route as MainPrivateListMediaTypeUsernameRouteRouteImport } from "./routes/_main/_private/list/$mediaType/$username.route";
import { Route as MainPrivateProfileUsernameHeaderIndexRouteImport } from "./routes/_main/_private/profile/$username/_header/index";
import { Route as MainPrivateProfileUsernameHeaderHistoryRouteImport } from "./routes/_main/_private/profile/$username/_header/history";
import { Route as MainPrivateProfileUsernameHeaderFollowsRouteImport } from "./routes/_main/_private/profile/$username/_header/follows";
import { Route as MainPrivateProfileUsernameHeaderFollowersRouteImport } from "./routes/_main/_private/profile/$username/_header/followers";
import { Route as MainPrivateDetailsEditMediaTypeMediaIdRouteImport } from "./routes/_main/_private/details/edit/$mediaType.$mediaId";
import { Route as MainPrivateDetailsMediaTypeJobNameRouteImport } from "./routes/_main/_private/details/$mediaType/$job.$name";

const MainPrivateProfileUsernameRouteImport = createFileRoute(
  "/_main/_private/profile/$username",
)();

const MainRoute = MainRouteImport.update({
  id: "/_main",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminRoute = AdminRouteImport.update({
  id: "/_admin",
  getParentRoute: () => rootRouteImport,
} as any);
const MainPublicRoute = MainPublicRouteImport.update({
  id: "/_public",
  getParentRoute: () => MainRoute,
} as any);
const MainPrivateRoute = MainPrivateRouteImport.update({
  id: "/_private",
  getParentRoute: () => MainRoute,
} as any);
const MainPublicIndexRoute = MainPublicIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => MainPublicRoute,
} as any);
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: "/admin/",
  path: "/admin/",
  getParentRoute: () => AdminRoute,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);
const MainUniversalPrivacyPolicyRoute =
  MainUniversalPrivacyPolicyRouteImport.update({
    id: "/_universal/privacy-policy",
    path: "/privacy-policy",
    getParentRoute: () => MainRoute,
  } as any);
const MainUniversalFeaturesRoute = MainUniversalFeaturesRouteImport.update({
  id: "/_universal/features",
  path: "/features",
  getParentRoute: () => MainRoute,
} as any);
const MainUniversalAboutRoute = MainUniversalAboutRouteImport.update({
  id: "/_universal/about",
  path: "/about",
  getParentRoute: () => MainRoute,
} as any);
const MainPublicResetPasswordRoute = MainPublicResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => MainPublicRoute,
} as any);
const MainPublicForgotPasswordRoute =
  MainPublicForgotPasswordRouteImport.update({
    id: "/forgot-password",
    path: "/forgot-password",
    getParentRoute: () => MainPublicRoute,
  } as any);
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: "/admin/users",
  path: "/admin/users",
  getParentRoute: () => AdminRoute,
} as any);
const AdminAdminOverviewRoute = AdminAdminOverviewRouteImport.update({
  id: "/admin/overview",
  path: "/admin/overview",
  getParentRoute: () => AdminRoute,
} as any);
const AdminAdminMediadleRoute = AdminAdminMediadleRouteImport.update({
  id: "/admin/mediadle",
  path: "/admin/mediadle",
  getParentRoute: () => AdminRoute,
} as any);
const AdminAdminMediaOverviewRoute = AdminAdminMediaOverviewRouteImport.update({
  id: "/admin/media-overview",
  path: "/admin/media-overview",
  getParentRoute: () => AdminRoute,
} as any);
const AdminAdminErrorLogsRoute = AdminAdminErrorLogsRouteImport.update({
  id: "/admin/error-logs",
  path: "/admin/error-logs",
  getParentRoute: () => AdminRoute,
} as any);
const AdminAdminArchivedTasksRoute = AdminAdminArchivedTasksRouteImport.update({
  id: "/admin/archived-tasks",
  path: "/admin/archived-tasks",
  getParentRoute: () => AdminRoute,
} as any);
const AdminAdminAdminTasksRoute = AdminAdminAdminTasksRouteImport.update({
  id: "/admin/admin-tasks",
  path: "/admin/admin-tasks",
  getParentRoute: () => AdminRoute,
} as any);
const AdminAdminAchievementsRoute = AdminAdminAchievementsRouteImport.update({
  id: "/admin/achievements",
  path: "/admin/achievements",
  getParentRoute: () => AdminRoute,
} as any);
const MainPrivateTrendsRouteRoute = MainPrivateTrendsRouteRouteImport.update({
  id: "/trends",
  path: "/trends",
  getParentRoute: () => MainPrivateRoute,
} as any);
const MainPrivateSearchRouteRoute = MainPrivateSearchRouteRouteImport.update({
  id: "/search",
  path: "/search",
  getParentRoute: () => MainPrivateRoute,
} as any);
const MainPrivatePlatformStatsRouteRoute =
  MainPrivatePlatformStatsRouteRouteImport.update({
    id: "/platform-stats",
    path: "/platform-stats",
    getParentRoute: () => MainPrivateRoute,
  } as any);
const MainPrivateMoviedleRouteRoute =
  MainPrivateMoviedleRouteRouteImport.update({
    id: "/moviedle",
    path: "/moviedle",
    getParentRoute: () => MainPrivateRoute,
  } as any);
const MainPrivateHallOfFameRouteRoute =
  MainPrivateHallOfFameRouteRouteImport.update({
    id: "/hall-of-fame",
    path: "/hall-of-fame",
    getParentRoute: () => MainPrivateRoute,
  } as any);
const MainPrivateComingNextRouteRoute =
  MainPrivateComingNextRouteRouteImport.update({
    id: "/coming-next",
    path: "/coming-next",
    getParentRoute: () => MainPrivateRoute,
  } as any);
const MainPrivateProfileUsernameRoute =
  MainPrivateProfileUsernameRouteImport.update({
    id: "/profile/$username",
    path: "/profile/$username",
    getParentRoute: () => MainPrivateRoute,
  } as any);
const MainPrivateSettingsIndexRoute =
  MainPrivateSettingsIndexRouteImport.update({
    id: "/settings/",
    path: "/settings/",
    getParentRoute: () => MainPrivateRoute,
  } as any);
const MainPrivateStatsUsernameRoute =
  MainPrivateStatsUsernameRouteImport.update({
    id: "/stats/$username",
    path: "/stats/$username",
    getParentRoute: () => MainPrivateRoute,
  } as any);
const MainPrivateAchievementsUsernameRoute =
  MainPrivateAchievementsUsernameRouteImport.update({
    id: "/achievements/$username",
    path: "/achievements/$username",
    getParentRoute: () => MainPrivateRoute,
  } as any);
const MainPrivateProfileUsernameHeaderRoute =
  MainPrivateProfileUsernameHeaderRouteImport.update({
    id: "/_header",
    getParentRoute: () => MainPrivateProfileUsernameRoute,
  } as any);
const MainPrivateDetailsMediaTypeMediaIdRoute =
  MainPrivateDetailsMediaTypeMediaIdRouteImport.update({
    id: "/details/$mediaType/$mediaId",
    path: "/details/$mediaType/$mediaId",
    getParentRoute: () => MainPrivateRoute,
  } as any);
const MainPrivateSettingsUploadsTaskIdRouteRoute =
  MainPrivateSettingsUploadsTaskIdRouteRouteImport.update({
    id: "/settings/uploads/$taskId",
    path: "/settings/uploads/$taskId",
    getParentRoute: () => MainPrivateRoute,
  } as any);
const MainPrivateListMediaTypeUsernameRouteRoute =
  MainPrivateListMediaTypeUsernameRouteRouteImport.update({
    id: "/list/$mediaType/$username",
    path: "/list/$mediaType/$username",
    getParentRoute: () => MainPrivateRoute,
  } as any);
const MainPrivateProfileUsernameHeaderIndexRoute =
  MainPrivateProfileUsernameHeaderIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => MainPrivateProfileUsernameHeaderRoute,
  } as any);
const MainPrivateProfileUsernameHeaderHistoryRoute =
  MainPrivateProfileUsernameHeaderHistoryRouteImport.update({
    id: "/history",
    path: "/history",
    getParentRoute: () => MainPrivateProfileUsernameHeaderRoute,
  } as any);
const MainPrivateProfileUsernameHeaderFollowsRoute =
  MainPrivateProfileUsernameHeaderFollowsRouteImport.update({
    id: "/follows",
    path: "/follows",
    getParentRoute: () => MainPrivateProfileUsernameHeaderRoute,
  } as any);
const MainPrivateProfileUsernameHeaderFollowersRoute =
  MainPrivateProfileUsernameHeaderFollowersRouteImport.update({
    id: "/followers",
    path: "/followers",
    getParentRoute: () => MainPrivateProfileUsernameHeaderRoute,
  } as any);
const MainPrivateDetailsEditMediaTypeMediaIdRoute =
  MainPrivateDetailsEditMediaTypeMediaIdRouteImport.update({
    id: "/details/edit/$mediaType/$mediaId",
    path: "/details/edit/$mediaType/$mediaId",
    getParentRoute: () => MainPrivateRoute,
  } as any);
const MainPrivateDetailsMediaTypeJobNameRoute =
  MainPrivateDetailsMediaTypeJobNameRouteImport.update({
    id: "/details/$mediaType/$job/$name",
    path: "/details/$mediaType/$job/$name",
    getParentRoute: () => MainPrivateRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/coming-next": typeof MainPrivateComingNextRouteRoute;
  "/hall-of-fame": typeof MainPrivateHallOfFameRouteRoute;
  "/moviedle": typeof MainPrivateMoviedleRouteRoute;
  "/platform-stats": typeof MainPrivatePlatformStatsRouteRoute;
  "/search": typeof MainPrivateSearchRouteRoute;
  "/trends": typeof MainPrivateTrendsRouteRoute;
  "/admin/achievements": typeof AdminAdminAchievementsRoute;
  "/admin/admin-tasks": typeof AdminAdminAdminTasksRoute;
  "/admin/archived-tasks": typeof AdminAdminArchivedTasksRoute;
  "/admin/error-logs": typeof AdminAdminErrorLogsRoute;
  "/admin/media-overview": typeof AdminAdminMediaOverviewRoute;
  "/admin/mediadle": typeof AdminAdminMediadleRoute;
  "/admin/overview": typeof AdminAdminOverviewRoute;
  "/admin/users": typeof AdminAdminUsersRoute;
  "/forgot-password": typeof MainPublicForgotPasswordRoute;
  "/reset-password": typeof MainPublicResetPasswordRoute;
  "/about": typeof MainUniversalAboutRoute;
  "/features": typeof MainUniversalFeaturesRoute;
  "/privacy-policy": typeof MainUniversalPrivacyPolicyRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/admin": typeof AdminAdminIndexRoute;
  "/": typeof MainPublicIndexRoute;
  "/achievements/$username": typeof MainPrivateAchievementsUsernameRoute;
  "/stats/$username": typeof MainPrivateStatsUsernameRoute;
  "/settings": typeof MainPrivateSettingsIndexRoute;
  "/list/$mediaType/$username": typeof MainPrivateListMediaTypeUsernameRouteRoute;
  "/settings/uploads/$taskId": typeof MainPrivateSettingsUploadsTaskIdRouteRoute;
  "/details/$mediaType/$mediaId": typeof MainPrivateDetailsMediaTypeMediaIdRoute;
  "/profile/$username": typeof MainPrivateProfileUsernameHeaderRouteWithChildren;
  "/details/$mediaType/$job/$name": typeof MainPrivateDetailsMediaTypeJobNameRoute;
  "/details/edit/$mediaType/$mediaId": typeof MainPrivateDetailsEditMediaTypeMediaIdRoute;
  "/profile/$username/followers": typeof MainPrivateProfileUsernameHeaderFollowersRoute;
  "/profile/$username/follows": typeof MainPrivateProfileUsernameHeaderFollowsRoute;
  "/profile/$username/history": typeof MainPrivateProfileUsernameHeaderHistoryRoute;
  "/profile/$username/": typeof MainPrivateProfileUsernameHeaderIndexRoute;
}
export interface FileRoutesByTo {
  "/coming-next": typeof MainPrivateComingNextRouteRoute;
  "/hall-of-fame": typeof MainPrivateHallOfFameRouteRoute;
  "/moviedle": typeof MainPrivateMoviedleRouteRoute;
  "/platform-stats": typeof MainPrivatePlatformStatsRouteRoute;
  "/search": typeof MainPrivateSearchRouteRoute;
  "/trends": typeof MainPrivateTrendsRouteRoute;
  "/admin/achievements": typeof AdminAdminAchievementsRoute;
  "/admin/admin-tasks": typeof AdminAdminAdminTasksRoute;
  "/admin/archived-tasks": typeof AdminAdminArchivedTasksRoute;
  "/admin/error-logs": typeof AdminAdminErrorLogsRoute;
  "/admin/media-overview": typeof AdminAdminMediaOverviewRoute;
  "/admin/mediadle": typeof AdminAdminMediadleRoute;
  "/admin/overview": typeof AdminAdminOverviewRoute;
  "/admin/users": typeof AdminAdminUsersRoute;
  "/forgot-password": typeof MainPublicForgotPasswordRoute;
  "/reset-password": typeof MainPublicResetPasswordRoute;
  "/about": typeof MainUniversalAboutRoute;
  "/features": typeof MainUniversalFeaturesRoute;
  "/privacy-policy": typeof MainUniversalPrivacyPolicyRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/admin": typeof AdminAdminIndexRoute;
  "/": typeof MainPublicIndexRoute;
  "/achievements/$username": typeof MainPrivateAchievementsUsernameRoute;
  "/stats/$username": typeof MainPrivateStatsUsernameRoute;
  "/settings": typeof MainPrivateSettingsIndexRoute;
  "/list/$mediaType/$username": typeof MainPrivateListMediaTypeUsernameRouteRoute;
  "/settings/uploads/$taskId": typeof MainPrivateSettingsUploadsTaskIdRouteRoute;
  "/details/$mediaType/$mediaId": typeof MainPrivateDetailsMediaTypeMediaIdRoute;
  "/profile/$username": typeof MainPrivateProfileUsernameHeaderIndexRoute;
  "/details/$mediaType/$job/$name": typeof MainPrivateDetailsMediaTypeJobNameRoute;
  "/details/edit/$mediaType/$mediaId": typeof MainPrivateDetailsEditMediaTypeMediaIdRoute;
  "/profile/$username/followers": typeof MainPrivateProfileUsernameHeaderFollowersRoute;
  "/profile/$username/follows": typeof MainPrivateProfileUsernameHeaderFollowsRoute;
  "/profile/$username/history": typeof MainPrivateProfileUsernameHeaderHistoryRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_admin": typeof AdminRouteWithChildren;
  "/_main": typeof MainRouteWithChildren;
  "/_main/_private": typeof MainPrivateRouteWithChildren;
  "/_main/_public": typeof MainPublicRouteWithChildren;
  "/_main/_private/coming-next": typeof MainPrivateComingNextRouteRoute;
  "/_main/_private/hall-of-fame": typeof MainPrivateHallOfFameRouteRoute;
  "/_main/_private/moviedle": typeof MainPrivateMoviedleRouteRoute;
  "/_main/_private/platform-stats": typeof MainPrivatePlatformStatsRouteRoute;
  "/_main/_private/search": typeof MainPrivateSearchRouteRoute;
  "/_main/_private/trends": typeof MainPrivateTrendsRouteRoute;
  "/_admin/admin/achievements": typeof AdminAdminAchievementsRoute;
  "/_admin/admin/admin-tasks": typeof AdminAdminAdminTasksRoute;
  "/_admin/admin/archived-tasks": typeof AdminAdminArchivedTasksRoute;
  "/_admin/admin/error-logs": typeof AdminAdminErrorLogsRoute;
  "/_admin/admin/media-overview": typeof AdminAdminMediaOverviewRoute;
  "/_admin/admin/mediadle": typeof AdminAdminMediadleRoute;
  "/_admin/admin/overview": typeof AdminAdminOverviewRoute;
  "/_admin/admin/users": typeof AdminAdminUsersRoute;
  "/_main/_public/forgot-password": typeof MainPublicForgotPasswordRoute;
  "/_main/_public/reset-password": typeof MainPublicResetPasswordRoute;
  "/_main/_universal/about": typeof MainUniversalAboutRoute;
  "/_main/_universal/features": typeof MainUniversalFeaturesRoute;
  "/_main/_universal/privacy-policy": typeof MainUniversalPrivacyPolicyRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/_admin/admin/": typeof AdminAdminIndexRoute;
  "/_main/_public/": typeof MainPublicIndexRoute;
  "/_main/_private/achievements/$username": typeof MainPrivateAchievementsUsernameRoute;
  "/_main/_private/stats/$username": typeof MainPrivateStatsUsernameRoute;
  "/_main/_private/settings/": typeof MainPrivateSettingsIndexRoute;
  "/_main/_private/list/$mediaType/$username": typeof MainPrivateListMediaTypeUsernameRouteRoute;
  "/_main/_private/settings/uploads/$taskId": typeof MainPrivateSettingsUploadsTaskIdRouteRoute;
  "/_main/_private/details/$mediaType/$mediaId": typeof MainPrivateDetailsMediaTypeMediaIdRoute;
  "/_main/_private/profile/$username": typeof MainPrivateProfileUsernameRouteWithChildren;
  "/_main/_private/profile/$username/_header": typeof MainPrivateProfileUsernameHeaderRouteWithChildren;
  "/_main/_private/details/$mediaType/$job/$name": typeof MainPrivateDetailsMediaTypeJobNameRoute;
  "/_main/_private/details/edit/$mediaType/$mediaId": typeof MainPrivateDetailsEditMediaTypeMediaIdRoute;
  "/_main/_private/profile/$username/_header/followers": typeof MainPrivateProfileUsernameHeaderFollowersRoute;
  "/_main/_private/profile/$username/_header/follows": typeof MainPrivateProfileUsernameHeaderFollowsRoute;
  "/_main/_private/profile/$username/_header/history": typeof MainPrivateProfileUsernameHeaderHistoryRoute;
  "/_main/_private/profile/$username/_header/": typeof MainPrivateProfileUsernameHeaderIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/coming-next"
    | "/hall-of-fame"
    | "/moviedle"
    | "/platform-stats"
    | "/search"
    | "/trends"
    | "/admin/achievements"
    | "/admin/admin-tasks"
    | "/admin/archived-tasks"
    | "/admin/error-logs"
    | "/admin/media-overview"
    | "/admin/mediadle"
    | "/admin/overview"
    | "/admin/users"
    | "/forgot-password"
    | "/reset-password"
    | "/about"
    | "/features"
    | "/privacy-policy"
    | "/api/auth/$"
    | "/admin"
    | "/"
    | "/achievements/$username"
    | "/stats/$username"
    | "/settings"
    | "/list/$mediaType/$username"
    | "/settings/uploads/$taskId"
    | "/details/$mediaType/$mediaId"
    | "/profile/$username"
    | "/details/$mediaType/$job/$name"
    | "/details/edit/$mediaType/$mediaId"
    | "/profile/$username/followers"
    | "/profile/$username/follows"
    | "/profile/$username/history"
    | "/profile/$username/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/coming-next"
    | "/hall-of-fame"
    | "/moviedle"
    | "/platform-stats"
    | "/search"
    | "/trends"
    | "/admin/achievements"
    | "/admin/admin-tasks"
    | "/admin/archived-tasks"
    | "/admin/error-logs"
    | "/admin/media-overview"
    | "/admin/mediadle"
    | "/admin/overview"
    | "/admin/users"
    | "/forgot-password"
    | "/reset-password"
    | "/about"
    | "/features"
    | "/privacy-policy"
    | "/api/auth/$"
    | "/admin"
    | "/"
    | "/achievements/$username"
    | "/stats/$username"
    | "/settings"
    | "/list/$mediaType/$username"
    | "/settings/uploads/$taskId"
    | "/details/$mediaType/$mediaId"
    | "/profile/$username"
    | "/details/$mediaType/$job/$name"
    | "/details/edit/$mediaType/$mediaId"
    | "/profile/$username/followers"
    | "/profile/$username/follows"
    | "/profile/$username/history";
  id:
    | "__root__"
    | "/_admin"
    | "/_main"
    | "/_main/_private"
    | "/_main/_public"
    | "/_main/_private/coming-next"
    | "/_main/_private/hall-of-fame"
    | "/_main/_private/moviedle"
    | "/_main/_private/platform-stats"
    | "/_main/_private/search"
    | "/_main/_private/trends"
    | "/_admin/admin/achievements"
    | "/_admin/admin/admin-tasks"
    | "/_admin/admin/archived-tasks"
    | "/_admin/admin/error-logs"
    | "/_admin/admin/media-overview"
    | "/_admin/admin/mediadle"
    | "/_admin/admin/overview"
    | "/_admin/admin/users"
    | "/_main/_public/forgot-password"
    | "/_main/_public/reset-password"
    | "/_main/_universal/about"
    | "/_main/_universal/features"
    | "/_main/_universal/privacy-policy"
    | "/api/auth/$"
    | "/_admin/admin/"
    | "/_main/_public/"
    | "/_main/_private/achievements/$username"
    | "/_main/_private/stats/$username"
    | "/_main/_private/settings/"
    | "/_main/_private/list/$mediaType/$username"
    | "/_main/_private/settings/uploads/$taskId"
    | "/_main/_private/details/$mediaType/$mediaId"
    | "/_main/_private/profile/$username"
    | "/_main/_private/profile/$username/_header"
    | "/_main/_private/details/$mediaType/$job/$name"
    | "/_main/_private/details/edit/$mediaType/$mediaId"
    | "/_main/_private/profile/$username/_header/followers"
    | "/_main/_private/profile/$username/_header/follows"
    | "/_main/_private/profile/$username/_header/history"
    | "/_main/_private/profile/$username/_header/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren;
  MainRoute: typeof MainRouteWithChildren;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_main": {
      id: "/_main";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof MainRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_admin": {
      id: "/_admin";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AdminRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_main/_public": {
      id: "/_main/_public";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof MainPublicRouteImport;
      parentRoute: typeof MainRoute;
    };
    "/_main/_private": {
      id: "/_main/_private";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof MainPrivateRouteImport;
      parentRoute: typeof MainRoute;
    };
    "/_main/_public/": {
      id: "/_main/_public/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof MainPublicIndexRouteImport;
      parentRoute: typeof MainPublicRoute;
    };
    "/_admin/admin/": {
      id: "/_admin/admin/";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof AdminAdminIndexRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_main/_universal/privacy-policy": {
      id: "/_main/_universal/privacy-policy";
      path: "/privacy-policy";
      fullPath: "/privacy-policy";
      preLoaderRoute: typeof MainUniversalPrivacyPolicyRouteImport;
      parentRoute: typeof MainRoute;
    };
    "/_main/_universal/features": {
      id: "/_main/_universal/features";
      path: "/features";
      fullPath: "/features";
      preLoaderRoute: typeof MainUniversalFeaturesRouteImport;
      parentRoute: typeof MainRoute;
    };
    "/_main/_universal/about": {
      id: "/_main/_universal/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof MainUniversalAboutRouteImport;
      parentRoute: typeof MainRoute;
    };
    "/_main/_public/reset-password": {
      id: "/_main/_public/reset-password";
      path: "/reset-password";
      fullPath: "/reset-password";
      preLoaderRoute: typeof MainPublicResetPasswordRouteImport;
      parentRoute: typeof MainPublicRoute;
    };
    "/_main/_public/forgot-password": {
      id: "/_main/_public/forgot-password";
      path: "/forgot-password";
      fullPath: "/forgot-password";
      preLoaderRoute: typeof MainPublicForgotPasswordRouteImport;
      parentRoute: typeof MainPublicRoute;
    };
    "/_admin/admin/users": {
      id: "/_admin/admin/users";
      path: "/admin/users";
      fullPath: "/admin/users";
      preLoaderRoute: typeof AdminAdminUsersRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/_admin/admin/overview": {
      id: "/_admin/admin/overview";
      path: "/admin/overview";
      fullPath: "/admin/overview";
      preLoaderRoute: typeof AdminAdminOverviewRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/_admin/admin/mediadle": {
      id: "/_admin/admin/mediadle";
      path: "/admin/mediadle";
      fullPath: "/admin/mediadle";
      preLoaderRoute: typeof AdminAdminMediadleRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/_admin/admin/media-overview": {
      id: "/_admin/admin/media-overview";
      path: "/admin/media-overview";
      fullPath: "/admin/media-overview";
      preLoaderRoute: typeof AdminAdminMediaOverviewRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/_admin/admin/error-logs": {
      id: "/_admin/admin/error-logs";
      path: "/admin/error-logs";
      fullPath: "/admin/error-logs";
      preLoaderRoute: typeof AdminAdminErrorLogsRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/_admin/admin/archived-tasks": {
      id: "/_admin/admin/archived-tasks";
      path: "/admin/archived-tasks";
      fullPath: "/admin/archived-tasks";
      preLoaderRoute: typeof AdminAdminArchivedTasksRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/_admin/admin/admin-tasks": {
      id: "/_admin/admin/admin-tasks";
      path: "/admin/admin-tasks";
      fullPath: "/admin/admin-tasks";
      preLoaderRoute: typeof AdminAdminAdminTasksRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/_admin/admin/achievements": {
      id: "/_admin/admin/achievements";
      path: "/admin/achievements";
      fullPath: "/admin/achievements";
      preLoaderRoute: typeof AdminAdminAchievementsRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/_main/_private/trends": {
      id: "/_main/_private/trends";
      path: "/trends";
      fullPath: "/trends";
      preLoaderRoute: typeof MainPrivateTrendsRouteRouteImport;
      parentRoute: typeof MainPrivateRoute;
    };
    "/_main/_private/search": {
      id: "/_main/_private/search";
      path: "/search";
      fullPath: "/search";
      preLoaderRoute: typeof MainPrivateSearchRouteRouteImport;
      parentRoute: typeof MainPrivateRoute;
    };
    "/_main/_private/platform-stats": {
      id: "/_main/_private/platform-stats";
      path: "/platform-stats";
      fullPath: "/platform-stats";
      preLoaderRoute: typeof MainPrivatePlatformStatsRouteRouteImport;
      parentRoute: typeof MainPrivateRoute;
    };
    "/_main/_private/moviedle": {
      id: "/_main/_private/moviedle";
      path: "/moviedle";
      fullPath: "/moviedle";
      preLoaderRoute: typeof MainPrivateMoviedleRouteRouteImport;
      parentRoute: typeof MainPrivateRoute;
    };
    "/_main/_private/hall-of-fame": {
      id: "/_main/_private/hall-of-fame";
      path: "/hall-of-fame";
      fullPath: "/hall-of-fame";
      preLoaderRoute: typeof MainPrivateHallOfFameRouteRouteImport;
      parentRoute: typeof MainPrivateRoute;
    };
    "/_main/_private/coming-next": {
      id: "/_main/_private/coming-next";
      path: "/coming-next";
      fullPath: "/coming-next";
      preLoaderRoute: typeof MainPrivateComingNextRouteRouteImport;
      parentRoute: typeof MainPrivateRoute;
    };
    "/_main/_private/profile/$username": {
      id: "/_main/_private/profile/$username";
      path: "/profile/$username";
      fullPath: "/profile/$username";
      preLoaderRoute: typeof MainPrivateProfileUsernameRouteImport;
      parentRoute: typeof MainPrivateRoute;
    };
    "/_main/_private/settings/": {
      id: "/_main/_private/settings/";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof MainPrivateSettingsIndexRouteImport;
      parentRoute: typeof MainPrivateRoute;
    };
    "/_main/_private/stats/$username": {
      id: "/_main/_private/stats/$username";
      path: "/stats/$username";
      fullPath: "/stats/$username";
      preLoaderRoute: typeof MainPrivateStatsUsernameRouteImport;
      parentRoute: typeof MainPrivateRoute;
    };
    "/_main/_private/achievements/$username": {
      id: "/_main/_private/achievements/$username";
      path: "/achievements/$username";
      fullPath: "/achievements/$username";
      preLoaderRoute: typeof MainPrivateAchievementsUsernameRouteImport;
      parentRoute: typeof MainPrivateRoute;
    };
    "/_main/_private/profile/$username/_header": {
      id: "/_main/_private/profile/$username/_header";
      path: "/profile/$username";
      fullPath: "/profile/$username";
      preLoaderRoute: typeof MainPrivateProfileUsernameHeaderRouteImport;
      parentRoute: typeof MainPrivateProfileUsernameRoute;
    };
    "/_main/_private/details/$mediaType/$mediaId": {
      id: "/_main/_private/details/$mediaType/$mediaId";
      path: "/details/$mediaType/$mediaId";
      fullPath: "/details/$mediaType/$mediaId";
      preLoaderRoute: typeof MainPrivateDetailsMediaTypeMediaIdRouteImport;
      parentRoute: typeof MainPrivateRoute;
    };
    "/_main/_private/settings/uploads/$taskId": {
      id: "/_main/_private/settings/uploads/$taskId";
      path: "/settings/uploads/$taskId";
      fullPath: "/settings/uploads/$taskId";
      preLoaderRoute: typeof MainPrivateSettingsUploadsTaskIdRouteRouteImport;
      parentRoute: typeof MainPrivateRoute;
    };
    "/_main/_private/list/$mediaType/$username": {
      id: "/_main/_private/list/$mediaType/$username";
      path: "/list/$mediaType/$username";
      fullPath: "/list/$mediaType/$username";
      preLoaderRoute: typeof MainPrivateListMediaTypeUsernameRouteRouteImport;
      parentRoute: typeof MainPrivateRoute;
    };
    "/_main/_private/profile/$username/_header/": {
      id: "/_main/_private/profile/$username/_header/";
      path: "/";
      fullPath: "/profile/$username/";
      preLoaderRoute: typeof MainPrivateProfileUsernameHeaderIndexRouteImport;
      parentRoute: typeof MainPrivateProfileUsernameHeaderRoute;
    };
    "/_main/_private/profile/$username/_header/history": {
      id: "/_main/_private/profile/$username/_header/history";
      path: "/history";
      fullPath: "/profile/$username/history";
      preLoaderRoute: typeof MainPrivateProfileUsernameHeaderHistoryRouteImport;
      parentRoute: typeof MainPrivateProfileUsernameHeaderRoute;
    };
    "/_main/_private/profile/$username/_header/follows": {
      id: "/_main/_private/profile/$username/_header/follows";
      path: "/follows";
      fullPath: "/profile/$username/follows";
      preLoaderRoute: typeof MainPrivateProfileUsernameHeaderFollowsRouteImport;
      parentRoute: typeof MainPrivateProfileUsernameHeaderRoute;
    };
    "/_main/_private/profile/$username/_header/followers": {
      id: "/_main/_private/profile/$username/_header/followers";
      path: "/followers";
      fullPath: "/profile/$username/followers";
      preLoaderRoute: typeof MainPrivateProfileUsernameHeaderFollowersRouteImport;
      parentRoute: typeof MainPrivateProfileUsernameHeaderRoute;
    };
    "/_main/_private/details/edit/$mediaType/$mediaId": {
      id: "/_main/_private/details/edit/$mediaType/$mediaId";
      path: "/details/edit/$mediaType/$mediaId";
      fullPath: "/details/edit/$mediaType/$mediaId";
      preLoaderRoute: typeof MainPrivateDetailsEditMediaTypeMediaIdRouteImport;
      parentRoute: typeof MainPrivateRoute;
    };
    "/_main/_private/details/$mediaType/$job/$name": {
      id: "/_main/_private/details/$mediaType/$job/$name";
      path: "/details/$mediaType/$job/$name";
      fullPath: "/details/$mediaType/$job/$name";
      preLoaderRoute: typeof MainPrivateDetailsMediaTypeJobNameRouteImport;
      parentRoute: typeof MainPrivateRoute;
    };
  }
}

interface AdminRouteChildren {
  AdminAdminAchievementsRoute: typeof AdminAdminAchievementsRoute;
  AdminAdminAdminTasksRoute: typeof AdminAdminAdminTasksRoute;
  AdminAdminArchivedTasksRoute: typeof AdminAdminArchivedTasksRoute;
  AdminAdminErrorLogsRoute: typeof AdminAdminErrorLogsRoute;
  AdminAdminMediaOverviewRoute: typeof AdminAdminMediaOverviewRoute;
  AdminAdminMediadleRoute: typeof AdminAdminMediadleRoute;
  AdminAdminOverviewRoute: typeof AdminAdminOverviewRoute;
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute;
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute;
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminAchievementsRoute: AdminAdminAchievementsRoute,
  AdminAdminAdminTasksRoute: AdminAdminAdminTasksRoute,
  AdminAdminArchivedTasksRoute: AdminAdminArchivedTasksRoute,
  AdminAdminErrorLogsRoute: AdminAdminErrorLogsRoute,
  AdminAdminMediaOverviewRoute: AdminAdminMediaOverviewRoute,
  AdminAdminMediadleRoute: AdminAdminMediadleRoute,
  AdminAdminOverviewRoute: AdminAdminOverviewRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
};

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren);

interface MainPrivateProfileUsernameHeaderRouteChildren {
  MainPrivateProfileUsernameHeaderFollowersRoute: typeof MainPrivateProfileUsernameHeaderFollowersRoute;
  MainPrivateProfileUsernameHeaderFollowsRoute: typeof MainPrivateProfileUsernameHeaderFollowsRoute;
  MainPrivateProfileUsernameHeaderHistoryRoute: typeof MainPrivateProfileUsernameHeaderHistoryRoute;
  MainPrivateProfileUsernameHeaderIndexRoute: typeof MainPrivateProfileUsernameHeaderIndexRoute;
}

const MainPrivateProfileUsernameHeaderRouteChildren: MainPrivateProfileUsernameHeaderRouteChildren =
  {
    MainPrivateProfileUsernameHeaderFollowersRoute:
      MainPrivateProfileUsernameHeaderFollowersRoute,
    MainPrivateProfileUsernameHeaderFollowsRoute:
      MainPrivateProfileUsernameHeaderFollowsRoute,
    MainPrivateProfileUsernameHeaderHistoryRoute:
      MainPrivateProfileUsernameHeaderHistoryRoute,
    MainPrivateProfileUsernameHeaderIndexRoute:
      MainPrivateProfileUsernameHeaderIndexRoute,
  };

const MainPrivateProfileUsernameHeaderRouteWithChildren =
  MainPrivateProfileUsernameHeaderRoute._addFileChildren(
    MainPrivateProfileUsernameHeaderRouteChildren,
  );

interface MainPrivateProfileUsernameRouteChildren {
  MainPrivateProfileUsernameHeaderRoute: typeof MainPrivateProfileUsernameHeaderRouteWithChildren;
}

const MainPrivateProfileUsernameRouteChildren: MainPrivateProfileUsernameRouteChildren =
  {
    MainPrivateProfileUsernameHeaderRoute:
      MainPrivateProfileUsernameHeaderRouteWithChildren,
  };

const MainPrivateProfileUsernameRouteWithChildren =
  MainPrivateProfileUsernameRoute._addFileChildren(
    MainPrivateProfileUsernameRouteChildren,
  );

interface MainPrivateRouteChildren {
  MainPrivateComingNextRouteRoute: typeof MainPrivateComingNextRouteRoute;
  MainPrivateHallOfFameRouteRoute: typeof MainPrivateHallOfFameRouteRoute;
  MainPrivateMoviedleRouteRoute: typeof MainPrivateMoviedleRouteRoute;
  MainPrivatePlatformStatsRouteRoute: typeof MainPrivatePlatformStatsRouteRoute;
  MainPrivateSearchRouteRoute: typeof MainPrivateSearchRouteRoute;
  MainPrivateTrendsRouteRoute: typeof MainPrivateTrendsRouteRoute;
  MainPrivateAchievementsUsernameRoute: typeof MainPrivateAchievementsUsernameRoute;
  MainPrivateStatsUsernameRoute: typeof MainPrivateStatsUsernameRoute;
  MainPrivateSettingsIndexRoute: typeof MainPrivateSettingsIndexRoute;
  MainPrivateListMediaTypeUsernameRouteRoute: typeof MainPrivateListMediaTypeUsernameRouteRoute;
  MainPrivateSettingsUploadsTaskIdRouteRoute: typeof MainPrivateSettingsUploadsTaskIdRouteRoute;
  MainPrivateDetailsMediaTypeMediaIdRoute: typeof MainPrivateDetailsMediaTypeMediaIdRoute;
  MainPrivateProfileUsernameRoute: typeof MainPrivateProfileUsernameRouteWithChildren;
  MainPrivateDetailsMediaTypeJobNameRoute: typeof MainPrivateDetailsMediaTypeJobNameRoute;
  MainPrivateDetailsEditMediaTypeMediaIdRoute: typeof MainPrivateDetailsEditMediaTypeMediaIdRoute;
}

const MainPrivateRouteChildren: MainPrivateRouteChildren = {
  MainPrivateComingNextRouteRoute: MainPrivateComingNextRouteRoute,
  MainPrivateHallOfFameRouteRoute: MainPrivateHallOfFameRouteRoute,
  MainPrivateMoviedleRouteRoute: MainPrivateMoviedleRouteRoute,
  MainPrivatePlatformStatsRouteRoute: MainPrivatePlatformStatsRouteRoute,
  MainPrivateSearchRouteRoute: MainPrivateSearchRouteRoute,
  MainPrivateTrendsRouteRoute: MainPrivateTrendsRouteRoute,
  MainPrivateAchievementsUsernameRoute: MainPrivateAchievementsUsernameRoute,
  MainPrivateStatsUsernameRoute: MainPrivateStatsUsernameRoute,
  MainPrivateSettingsIndexRoute: MainPrivateSettingsIndexRoute,
  MainPrivateListMediaTypeUsernameRouteRoute:
    MainPrivateListMediaTypeUsernameRouteRoute,
  MainPrivateSettingsUploadsTaskIdRouteRoute:
    MainPrivateSettingsUploadsTaskIdRouteRoute,
  MainPrivateDetailsMediaTypeMediaIdRoute:
    MainPrivateDetailsMediaTypeMediaIdRoute,
  MainPrivateProfileUsernameRoute: MainPrivateProfileUsernameRouteWithChildren,
  MainPrivateDetailsMediaTypeJobNameRoute:
    MainPrivateDetailsMediaTypeJobNameRoute,
  MainPrivateDetailsEditMediaTypeMediaIdRoute:
    MainPrivateDetailsEditMediaTypeMediaIdRoute,
};

const MainPrivateRouteWithChildren = MainPrivateRoute._addFileChildren(
  MainPrivateRouteChildren,
);

interface MainPublicRouteChildren {
  MainPublicForgotPasswordRoute: typeof MainPublicForgotPasswordRoute;
  MainPublicResetPasswordRoute: typeof MainPublicResetPasswordRoute;
  MainPublicIndexRoute: typeof MainPublicIndexRoute;
}

const MainPublicRouteChildren: MainPublicRouteChildren = {
  MainPublicForgotPasswordRoute: MainPublicForgotPasswordRoute,
  MainPublicResetPasswordRoute: MainPublicResetPasswordRoute,
  MainPublicIndexRoute: MainPublicIndexRoute,
};

const MainPublicRouteWithChildren = MainPublicRoute._addFileChildren(
  MainPublicRouteChildren,
);

interface MainRouteChildren {
  MainPrivateRoute: typeof MainPrivateRouteWithChildren;
  MainPublicRoute: typeof MainPublicRouteWithChildren;
  MainUniversalAboutRoute: typeof MainUniversalAboutRoute;
  MainUniversalFeaturesRoute: typeof MainUniversalFeaturesRoute;
  MainUniversalPrivacyPolicyRoute: typeof MainUniversalPrivacyPolicyRoute;
}

const MainRouteChildren: MainRouteChildren = {
  MainPrivateRoute: MainPrivateRouteWithChildren,
  MainPublicRoute: MainPublicRouteWithChildren,
  MainUniversalAboutRoute: MainUniversalAboutRoute,
  MainUniversalFeaturesRoute: MainUniversalFeaturesRoute,
  MainUniversalPrivacyPolicyRoute: MainUniversalPrivacyPolicyRoute,
};

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  MainRoute: MainRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.ts";
import type { startInstance } from "./start.ts";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
