import {AchievementDifficulty, MediaType} from "@/lib/server/utils/enums";


export const booksAchievements = [
    {
        codeName: "completed_books",
        name: "Bibliophile Conqueror",
        description: "Awarded for completing books, because every finished book is a new world conquered in your literary journey!",
        mediaType: MediaType.BOOKS,
        tiers: [
            { criteria: { count: 10 }, difficulty: AchievementDifficulty.BRONZE },
            { criteria: { count: 30 }, difficulty: AchievementDifficulty.SILVER },
            { criteria: { count: 80 }, difficulty: AchievementDifficulty.GOLD },
            { criteria: { count: 150 }, difficulty: AchievementDifficulty.PLATINUM },
        ],
    },
    {
        codeName: "rated_books",
        name: "Rating Wizard",
        description: "Awarded for rating books, because your insights can turn a hidden gem into a bestseller!",
        mediaType: MediaType.BOOKS,
        tiers: [
            { criteria: { count: 10 }, difficulty: AchievementDifficulty.BRONZE },
            { criteria: { count: 30 }, difficulty: AchievementDifficulty.SILVER },
            { criteria: { count: 50 }, difficulty: AchievementDifficulty.GOLD },
            { criteria: { count: 100 }, difficulty: AchievementDifficulty.PLATINUM },
        ],
    },
    {
        codeName: "comment_books",
        name: "Commentary Bard",
        description: "Awarded for commenting books, because every opinion adds a new layer to the storytelling tapestry!",
        mediaType: MediaType.BOOKS,
        tiers: [
            { criteria: { count: 10 }, difficulty: AchievementDifficulty.BRONZE },
            { criteria: { count: 30 }, difficulty: AchievementDifficulty.SILVER },
            { criteria: { count: 50 }, difficulty: AchievementDifficulty.GOLD },
            { criteria: { count: 100 }, difficulty: AchievementDifficulty.PLATINUM },
        ],
    },
    {
        codeName: "author_books",
        name: "Author Aficionado",
        description: "Awarded for completing books from the same author, showing your unwavering devotion to their literary magic!",
        mediaType: MediaType.BOOKS,
        tiers: [
            { criteria: { count: 3 }, difficulty: AchievementDifficulty.BRONZE },
            { criteria: { count: 5 }, difficulty: AchievementDifficulty.SILVER },
            { criteria: { count: 8 }, difficulty: AchievementDifficulty.GOLD },
            { criteria: { count: 12 }, difficulty: AchievementDifficulty.PLATINUM },
        ],
    },
    {
        codeName: "lang_books",
        name: "Linguistic Explorer",
        description: "Awarded for completing books in 2 different languages, because you’re mastering the art of storytelling across cultures!",
        mediaType: MediaType.BOOKS,
        value: 2,
        tiers: [
            { criteria: { count: 1 }, difficulty: AchievementDifficulty.BRONZE },
            { criteria: { count: 3 }, difficulty: AchievementDifficulty.SILVER },
            { criteria: { count: 5 }, difficulty: AchievementDifficulty.GOLD },
            { criteria: { count: 8 }, difficulty: AchievementDifficulty.PLATINUM },
        ],
    },
    {
        codeName: "short_books",
        name: "Quick Read Guru",
        description: "Awarded for completing books with less than 150 pages, because you appreciate the art of concise " +
            "storytelling that gets straight to the point!",
        mediaType: MediaType.BOOKS,
        value: 150,
        tiers: [
            { criteria: { count: 3 }, difficulty: AchievementDifficulty.BRONZE },
            { criteria: { count: 5 }, difficulty: AchievementDifficulty.SILVER },
            { criteria: { count: 8 }, difficulty: AchievementDifficulty.GOLD },
            { criteria: { count: 12 }, difficulty: AchievementDifficulty.PLATINUM },
        ],
    },
    {
        codeName: "long_books",
        name: "Epic Page Turner",
        description: "Awarded for completing books with more than 800 pages, proving you have the stamina for literary marathon sessions!",
        mediaType: MediaType.BOOKS,
        value: 800,
        tiers: [
            { criteria: { count: 1 }, difficulty: AchievementDifficulty.BRONZE },
            { criteria: { count: 2 }, difficulty: AchievementDifficulty.SILVER },
            { criteria: { count: 3 }, difficulty: AchievementDifficulty.GOLD },
            { criteria: { count: 4 }, difficulty: AchievementDifficulty.PLATINUM },
        ],
    },
    {
        codeName: "classic_books",
        name: "Classic Crusader",
        description: "Awarded for completing Classic books, because you’re embracing the timeless tales that shaped literature!",
        mediaType: MediaType.BOOKS,
        value: "Classic",
        tiers: [
            { criteria: { count: 3 }, difficulty: AchievementDifficulty.BRONZE },
            { criteria: { count: 5 }, difficulty: AchievementDifficulty.SILVER },
            { criteria: { count: 8 }, difficulty: AchievementDifficulty.GOLD },
            { criteria: { count: 12 }, difficulty: AchievementDifficulty.PLATINUM },
        ],
    },
    {
        codeName: "young_adult_books",
        name: "Young Adult Adventurer",
        description: "Awarded for completing Young Adult books, because sometimes the journey to self-discovery is just as thrilling!",
        mediaType: MediaType.BOOKS,
        value: "Young adult",
        tiers: [
            { criteria: { count: 3 }, difficulty: AchievementDifficulty.BRONZE },
            { criteria: { count: 5 }, difficulty: AchievementDifficulty.SILVER },
            { criteria: { count: 8 }, difficulty: AchievementDifficulty.GOLD },
            { criteria: { count: 12 }, difficulty: AchievementDifficulty.PLATINUM },
        ],
    },
    {
        codeName: "crime_books",
        name: "Serial Seeker",
        description: "Awarded for completing Crime books, because you thrive on plot twists and heart-pounding suspense!",
        mediaType: MediaType.BOOKS,
        value: "Crime",
        tiers: [
            { criteria: { count: 3 }, difficulty: AchievementDifficulty.BRONZE },
            { criteria: { count: 5 }, difficulty: AchievementDifficulty.SILVER },
            { criteria: { count: 8 }, difficulty: AchievementDifficulty.GOLD },
            { criteria: { count: 12 }, difficulty: AchievementDifficulty.PLATINUM },
        ],
    },
    {
        codeName: "fantasy_books",
        name: "Fantasy Realm Adventurer",
        description: "Awarded for completing Fantasy books, because you’ve traversed enchanted lands and battled mythical creatures like a true hero!",
        mediaType: MediaType.BOOKS,
        value: "Fantasy",
        tiers: [
            { criteria: { count: 3 }, difficulty: AchievementDifficulty.BRONZE },
            { criteria: { count: 5 }, difficulty: AchievementDifficulty.SILVER },
            { criteria: { count: 8 }, difficulty: AchievementDifficulty.GOLD },
            { criteria: { count: 12 }, difficulty: AchievementDifficulty.PLATINUM },
        ],
    },
] as const;